services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  php:
    build: 
      context: ./docker/php
    volumes:
      - .:/var/www/html
